source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'bootstrap-sass', '~> 3.3.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise', '~> 3.5.1'
gem 'puma'
gem "paperclip", "~> 4.2"

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

group :test do 
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace'
  gem 'guard-minitest', '2.3.1'
end

